MACHINE_IP="192.168.67.2"
DOCKER_BRIDGE="172.22.0.1/16"
CLUSTER_USER="admin"

Vagrant.configure("2") do |config|
  config.vm.box = "http://ernelsondt.usersys.redhat.com:11080/nskcentos.box"
  config.vm.hostname = "catasb"
  config.vm.network :private_network, ip: MACHINE_IP

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 4096
    libvirt.cpus = 2
  end

  config.vm.synced_folder ".", "/shared", :type => "nfs"
  config.vm.provision :shell, :path => "provision.sh",
    :args => [DOCKER_BRIDGE]
end
