MACHINE_IP="192.168.67.2"
CLUSTER_USER="admin"
BASE_BOX="http://ernelsondt.usersys.redhat.com:11080/catasb/stage1/box"

if !ENV['DOCKERHUB_USER'] || !ENV['DOCKERHUB_PASS']
  puts "ERROR: Missing dockerhub credentials env vars:"
  puts "-> DOCKERHUB_USER"
  puts "-> DOCKERHUB_PASS"
  exit 1
end

Vagrant.configure("2") do |config|
  config.vm.box = BASE_BOX
  config.vm.hostname = "catasb"
  config.vm.network :private_network, ip: MACHINE_IP

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 4096
    libvirt.cpus = 2
  end

  config.vm.synced_folder ".", "/shared", :type => "nfs", :nfs_udp => false

  prov_env = {
    DOCKERHUB_USER: ENV['DOCKERHUB_USER'],
    DOCKERHUB_PASS: ENV['DOCKERHUB_PASS']
  }

  if ENV['BUILD_CATALOG']
    prov_env['BUILD_CATALOG'] = 1
  end

  config.vm.provision :shell, :path => "provision.sh",
    :env => prov_env, :args => [MACHINE_IP]
end
